name: 'greyson  '
favicon: null
layout_spectrum: 0.27262556506320834
typography_spectrum: 0.61971
title: Hello Grey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf9f5'
    - '#ddd9da'
    - '#111516'
    - '#aba1a0'
    - '#2c3739'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.9867595545947552
  rhythmicContrast: 0.75
purpose: []
