name: 'greyson  '
favicon: null
layout_spectrum: 0.27262556506320834
typography_spectrum: 0.5464946082793176
title: greyson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.15228634886443615
  lightness: 0.8144309474155307
  saturation: 0.9867595545947552
  rhythmicContrast: 0.2079635034315288
purpose: []
